const A='art/';
const decks={
 rio:{name:'METAL RIO',flag:'MR',color:'#00eaff',art:'metal_rio.jpg',enemy:'vulcao',leader:'Mestre da Regulagem',leaderText:'+2 para uma máquina CNC por rodada.',cards:[
  {n:'REGULADORA CNC',p:8,t:'Operadora',l:0,r:'ÉPICA',a:'rio_01.jpg',h:'Dá +3 para uma máquina CNC nesta linha.'},
  {n:'TORNO CNC',p:11,t:'Máquina',l:0,r:'ÉPICA',a:'rio_02.jpg',h:'Recebe +2 se houver uma Reguladora na linha.'},
  {n:'INDEX GU800',p:14,t:'Máquina pesada',l:0,r:'LENDÁRIA',a:'rio_03.jpg',h:'Produz +2 adicionais no fim da rodada.'},
  {n:'EMPILHADEIRA TURBO',p:8,t:'Logística',l:1,r:'RARA',a:'rio_04.jpg',h:'Pode ser jogada em qualquer fileira.'},
  {n:'INSPETORA FINAL',p:7,t:'Qualidade',l:2,r:'RARA',a:'rio_05.jpg',h:'Protege uma máquina contra sabotagem.'},
  {n:'SETUP PERFEITO',p:7,t:'Ação',l:0,r:'ÉPICA',a:'rio_06.jpg',h:'Todas as cartas da linha recebem +1.'},
  {n:'PONTE ROLANTE',p:9,t:'Logística',l:1,r:'RARA',a:'rio_07.jpg',h:'Move a máquina mais forte para esta linha.'},
  {n:'MANUTENÇÃO',p:6,t:'Equipe',l:2,r:'COMUM',a:'rio_08.jpg',h:'Recupera +4 de uma máquina danificada.'},
  {n:'GIOVANI',p:10,t:'Regulador',l:0,r:'ÉPICA',a:'friend_giovani.jpg',h:'A máquina aliada mais fraca recebe +2.'}]},
 vulcao:{name:'FÁBRICA VULCÃO',flag:'FV',color:'#ff304f',art:'fabrica_vulcao.jpg',enemy:'rio',leader:'Mestre Fundidor',leaderText:'A primeira máquina pesada recebe +3.',cards:[
  {n:'MESTRE FUNDIDOR',p:9,t:'Equipe',l:0,r:'ÉPICA',a:'vulcao_01.jpg',h:'Fortalece todas as cartas de fundição.'},{n:'FORNO VULCÃO',p:15,t:'Máquina pesada',l:0,r:'LENDÁRIA',a:'vulcao_02.jpg',h:'Perde 2 após cada rodada vencida.'},{n:'PRENSA TITÃ',p:12,t:'Máquina',l:0,r:'ÉPICA',a:'vulcao_03.jpg',h:'Ganha +2 contra máquinas leves.'},{n:'LINGOTE QUENTE',p:7,t:'Material',l:0,r:'RARA',a:'vulcao_04.jpg',h:'A próxima máquina recebe +3.'},{n:'GUINDASTE PESADO',p:10,t:'Logística',l:1,r:'RARA',a:'vulcao_05.jpg',h:'Puxa uma máquina da reserva.'},{n:'QUALIDADE BRUTA',p:6,t:'Qualidade',l:2,r:'COMUM',a:'vulcao_06.jpg',h:'Impede uma redução de poder.'},{n:'TÊMPERA TOTAL',p:8,t:'Ação',l:2,r:'ÉPICA',a:'vulcao_07.jpg',h:'Duplica o bônus de material.'},{n:'AÇO INCANDESCENTE',p:11,t:'Material',l:0,r:'RARA',a:'vulcao_08.jpg',h:'Causa -2 na linha rival.'},{n:'JONATHAN',p:10,t:'Fundidor',l:0,r:'ÉPICA',a:'friend_jonathan.jpg',h:'A carta rival mais forte desta linha perde 2.'}]},
 turbo:{name:'LOGÍSTICA TURBO',flag:'LT',color:'#ffe600',art:'logistica_turbo.jpg',enemy:'vulcao',leader:'Piloto Turbo',leaderText:'Uma carta pode mudar de fileira por rodada.',cards:[
  {n:'PILOTO TURBO',p:8,t:'Operadora',l:1,r:'ÉPICA',a:'turbo_01.jpg',h:'A logística mais forte recebe +2.'},{n:'EMPILHADEIRA ELÉTRICA',p:10,t:'Máquina',l:1,r:'RARA',a:'turbo_02.jpg',h:'Recebe +2 se jogada após um pallet.'},{n:'DOCA EXPRESSA',p:7,t:'Local',l:1,r:'RARA',a:'turbo_03.jpg',h:'Permite jogar uma carta adicional.'},{n:'PONTE ROLANTE',p:9,t:'Máquina',l:1,r:'ÉPICA',a:'turbo_04.jpg',h:'Move a carta mais forte entre linhas.'},{n:'ESTOQUISTA',p:6,t:'Equipe',l:1,r:'COMUM',a:'turbo_05.jpg',h:'Compra uma carta de material ou carga.'},{n:'PALLETS URGENTES',p:8,t:'Carga',l:1,r:'RARA',a:'turbo_06.jpg',h:'Ganha +1 por carta de logística.'},{n:'CAMINHÃO DE CARGA',p:12,t:'Máquina pesada',l:1,r:'ÉPICA',a:'turbo_07.jpg',h:'Dá +6 para uma fileira vizinha.'},{n:'ROTA OTIMIZADA',p:5,t:'Ação',l:2,r:'COMUM',a:'turbo_08.jpg',h:'Dá +2 para todas as cargas.'},{n:'JÚLIO',p:10,t:'Batedor',l:1,r:'ÉPICA',a:'friend_julio.jpg',h:'A carta de Logística mais fraca recebe +2.'}]},
 elite:{name:'MANUTENÇÃO ELITE',flag:'ME',color:'#d946ff',art:'manutencao_elite.jpg',enemy:'rio',leader:'Técnica Elite',leaderText:'Restaura +4 de uma máquina por rodada.',cards:[
  {n:'TÉCNICA ELITE',p:9,t:'Engenheira',l:2,r:'LENDÁRIA',a:'elite_01.jpg',h:'Repara e protege uma máquina.'},{n:'OFICINA MÓVEL',p:10,t:'Máquina',l:2,r:'ÉPICA',a:'elite_02.jpg',h:'Todas as equipes recebem +1.'},{n:'LUBRIFICAÇÃO',p:6,t:'Ação',l:2,r:'COMUM',a:'elite_03.jpg',h:'Uma máquina ganha +1 por rodada.'},{n:'CALIBRADOR DIGITAL',p:8,t:'Ferramenta',l:2,r:'RARA',a:'elite_04.jpg',h:'Copia o bônus de outra ferramenta.'},{n:'SOLDADOR',p:7,t:'Equipe',l:2,r:'RARA',a:'elite_05.jpg',h:'Recupera uma máquina destruída.'},{n:'PEÇA SOBRESSALENTE',p:5,t:'Material',l:2,r:'COMUM',a:'elite_06.jpg',h:'Anula Ferramenta Quebrada.'},{n:'MECÂNICO CHEFE',p:12,t:'Equipe',l:2,r:'ÉPICA',a:'elite_07.jpg',h:'Dá +2 a todas as máquinas reparadas.'},{n:'REPARO URGENTE',p:9,t:'Ação',l:2,r:'RARA',a:'elite_08.jpg',h:'Restaura poder e joga novamente.'},{n:'GABRIEL',p:10,t:'Técnico noturno',l:2,r:'ÉPICA',a:'friend_gabriel.jpg',h:'A carta de Qualidade mais fraca recebe +2.'}]}
};
let deck='rio',opponent='vulcao',hand=[],aiHand=[],me=[[],[],[]],ai=[[],[],[]],round=1,wins=0,losses=0,busy=false,selected=null,selectedLane=null,difficulty='normal',tutorialStep=0,editingDeck=[];
let customDecks={},career={matches:0,wins:0,scrap:0,lastReward:0,ownedFrames:['frame-fornalha'],selectedFrame:'random',ownedTracks:[0],selectedTrack:-1};
let meBonus=[0,0,0],aiBonus=[0,0,0],meShield=[false,false,false],aiShield=[false,false,false];
let mePending=0,aiPending=0,lastMe=null,lastAi=null,meLeaderUsed=false,aiLeaderUsed=false,fornoPenaltyMe=0,fornoPenaltyAi=0;
let soundOn=true,trackIndex=-1,actionHistory=[];
const TRACKS=['audio/forja_industrial.ogg','audio/forja_rock.ogg','audio/forja_eletronica.ogg'];
const TRACK_INFO=[{n:'INDUSTRIAL DA FORJA',price:0,color:'#ffb44a',note:'Metal, vapor e batida de fábrica.'},{n:'ROCK DO ALTO-FORNO',price:250,color:'#ff425c',note:'Guitarras pesadas para o combate.'},{n:'ELETRÔNICA CNC',price:400,color:'#28e4ff',note:'Pulso futurista e precisão digital.'}];
const FRAMES=[{c:'frame-fornalha',n:'FORNALHA DE BRONZE',price:0,color:'#ffae45'},{c:'frame-cobalto',n:'AÇO COBALTO',price:250,color:'#35e9ff'},{c:'frame-hidraulica',n:'PRENSA HIDRÁULICA',price:400,color:'#ff425d'},{c:'frame-reator',n:'REATOR VIOLETA',price:600,color:'#df56ff'}];
const FRIENDS=new Set(['JÚLIO','GIOVANI','JONATHAN','GABRIEL']);
const L=['USINAGEM','LOGÍSTICA','QUALIDADE'],q=s=>document.querySelector(s),mix=a=>[...a].sort(()=>Math.random()-.5);
const flat=a=>a.flat(),laneValue=(a,b,i)=>a[i].reduce((s,c)=>s+c.p,0)+b[i],total=(a,b)=>flat(a).reduce((s,c)=>s+c.p,0)+b.reduce((s,n)=>s+n,0);
const copy=(c,penalty=0)=>({...c,p:Math.max(1,c.p-(c.n==='FORNO VULCÃO'?penalty:0)),base:c.p,repaired:false,lubed:false});
function defaultDeck(key){const cards=decks[key].cards,friend=cards.find(c=>FRIENDS.has(c.n));return[friend,...cards.filter(c=>c!==friend).slice(0,5)].map(c=>c.n)}
function loadProgress(){try{customDecks=JSON.parse(localStorage.getItem('forjaDecksV14')||'{}');career={...career,...JSON.parse(localStorage.getItem('forjaCareerV14')||'{}')}}catch(e){customDecks={}}career.ownedFrames=Array.isArray(career.ownedFrames)?career.ownedFrames.filter(x=>FRAMES.some(f=>f.c===x)):['frame-fornalha'];if(!career.ownedFrames.includes('frame-fornalha'))career.ownedFrames.unshift('frame-fornalha');if(career.selectedFrame!=='random'&&!career.ownedFrames.includes(career.selectedFrame))career.selectedFrame='random';career.ownedTracks=Array.isArray(career.ownedTracks)?career.ownedTracks.filter(x=>Number.isInteger(x)&&TRACK_INFO[x]):[0];if(!career.ownedTracks.includes(0))career.ownedTracks.unshift(0);if(career.selectedTrack!==-1&&!career.ownedTracks.includes(career.selectedTrack))career.selectedTrack=-1;Object.keys(decks).forEach(k=>{const valid=(customDecks[k]||[]).filter(n=>decks[k].cards.some(c=>c.n===n));const friend=decks[k].cards.find(c=>FRIENDS.has(c.n)).n;if(valid.length!==6||!valid.includes(friend))customDecks[k]=defaultDeck(k)})}
function saveProgress(){try{localStorage.setItem('forjaDecksV14',JSON.stringify(customDecks));localStorage.setItem('forjaCareerV14',JSON.stringify(career))}catch(e){}}
function updateCareer(){q('#careerScrap').textContent=career.scrap;q('#careerWins').textContent=career.wins;q('#careerMatches').textContent=career.matches}
function deal(key,side){const penalty=side==='me'?fornoPenaltyMe:fornoPenaltyAi,names=side==='me'?customDecks[key]:null,source=names?names.map(n=>decks[key].cards.find(c=>c.n===n)).filter(Boolean):decks[key].cards,pool=mix(source),picked=pool.slice(0,6),friend=pool.find(c=>FRIENDS.has(c.n));if(friend&&!picked.includes(friend))picked[picked.length-1]=friend;return picked.map(c=>copy(c,penalty))}
function state(side){return side==='me'?{own:me,enemy:ai,bonus:meBonus,enemyBonus:aiBonus,shield:meShield,enemyShield:aiShield,key:deck}:{own:ai,enemy:me,bonus:aiBonus,enemyBonus:meBonus,shield:aiShield,enemyShield:meShield,key:opponent}}
function sfx(name){try{if(window.NativeAudio)NativeAudio.sfx(name)}catch(e){}}
function recordAction(text,side,cardName){const who=side==='ai'?'RIVAL':'VOCÊ',entry={who,card:cardName||'EFEITO',text,enemy:side==='ai'};actionHistory.unshift(entry);actionHistory=actionHistory.slice(0,16);q('#lastAction').textContent=`${who} • ${entry.card}: ${text}`}
function effect(text,side='me',kind='bonus',cardName=''){recordAction(text,side,cardName);const box=q('#effectToast');box.textContent=(side==='ai'?'RIVAL • ':'')+text;box.className='effect-toast '+(side==='ai'?'enemy-effect ':'')+'show';setTimeout(()=>box.classList.remove('show'),1500);q('#tip').textContent=text;sfx(kind)}
function shortEffect(text){let m=text.match(/perdeu\s+(\d+)/i);if(m)return'-'+m[1];m=text.match(/\+(\d+)/);if(m)return'+'+m[1];if(/comprad|reserva/i.test(text))return'+1 CARTA';if(/novamente|outra carta/i.test(text))return'JOGADA EXTRA';if(/proteg/i.test(text))return'PROTEGIDA';if(/movid|posicionad/i.test(text))return'MOVIDA';return'ATIVADA'}
function laneEffect(side,lane,text){const rows=q(side==='ai'?'#enemyRows':'#playerRows'),row=rows.children[lane];if(!row)return;const pop=document.createElement('span');pop.className='lane-effect';pop.textContent=shortEffect(text);row.append(pop);setTimeout(()=>pop.remove(),1300)}
function showBattleCard(c,side,lane,done){const stage=q('#playStage'),host=q('#playStageCard'),enemy=side==='ai',card=make(c,enemy,false);stage.style.setProperty('--deck-color',decks[deck].color);stage.style.setProperty('--enemy-color',decks[opponent].color);card.onclick=null;card.classList.add('battle-card');host.innerHTML='';host.append(card);q('#playStageTitle').textContent=enemy?'RIVAL JOGOU':'SUA JOGADA';q('#playStageAbility').textContent=c.n+' • '+c.h;stage.className='play-stage '+(enemy?'enemy-play':'');setTimeout(()=>{const rows=q(enemy?'#enemyRows':'#playerRows'),target=rows.children[lane],r=target?target.getBoundingClientRect():{left:innerWidth/2,top:innerHeight/2,width:0,height:0},dx=r.left+r.width/2-innerWidth/2,dy=r.top+r.height/2-innerHeight/2;stage.classList.add('flying');if(card.animate){const a=card.animate([{transform:'translate(0,0) scale(1)',opacity:1},{transform:`translate(${dx}px,${dy}px) scale(.18)`,opacity:.78}],{duration:440,easing:'cubic-bezier(.2,.8,.2,1)',fill:'forwards'});a.onfinish=()=>{stage.className='play-stage hidden';host.innerHTML='';done()}}else setTimeout(()=>{stage.className='play-stage hidden';host.innerHTML='';done()},440)},720)}
function make(c,enemy,small){const d=decks[enemy?opponent:deck],e=document.createElement('button');e.className='card '+(small?'small-card ':'')+(enemy?'enemy-card':'');e.style.setProperty('--frame',d.color);e.innerHTML=`<div class="card-art" style="background-image:url('${A+c.a}')"></div><i class="power">${c.p}</i><span class="flag">${d.flag}</span><span class="rarity">◆ ${c.r}</span><div class="card-copy"><b>${c.n}</b><small>${c.t} • ${L[c.l]}</small><em>${c.h}</em></div>`;if(small)e.onclick=ev=>{ev.stopPropagation();inspectCard(c,enemy)};else if(!enemy)e.onclick=()=>pick(e,c);return e}
function inspectCard(c,enemy){const host=q('#inspectCardHost'),card=make(c,enemy,false);card.onclick=null;card.classList.add('inspect-card');host.innerHTML='';host.append(card);q('#inspectOwner').textContent=enemy?'CARTA DO RIVAL':'SUA CARTA';q('#inspectOwner').className=enemy?'enemy-label':'';q('#inspectAbility').textContent=c.h;q('#inspectEffect').textContent=c.lastEffect||'Esta carta ainda não ativou uma ação registrada.';q('#cardInspect').classList.remove('hidden')}
function closeInspect(){q('#cardInspect').classList.add('hidden')}
function openHistory(){const list=q('#historyList');list.innerHTML=actionHistory.length?actionHistory.map(x=>`<div class="${x.enemy?'enemy-log':''}"><small>${x.who}</small><b>${x.card}</b><p>${x.text}</p></div>`).join(''):'<p class="empty-log">Nenhuma carta foi jogada ainda.</p>';q('#historyModal').classList.remove('hidden')}
function closeHistory(){q('#historyModal').classList.add('hidden')}
function renderDeckBuilder(){const grid=q('#deckGrid'),friend=decks[deck].cards.find(c=>FRIENDS.has(c.n)).n;q('#deckModalTitle').textContent=decks[deck].name;q('#deckCount').textContent=editingDeck.length+' / 6 CARTAS';q('#deckCount').classList.toggle('invalid',editingDeck.length!==6);grid.innerHTML='';decks[deck].cards.forEach(raw=>{const c=copy(raw),wrap=document.createElement('div'),card=make(c,false,false),button=document.createElement('button'),selected=editingDeck.includes(c.n),locked=c.n===friend;wrap.className='deck-choice '+(selected?'selected ':'')+(locked?'locked':'');card.classList.add('gallery-card');card.onclick=()=>inspectCard(c,false);button.textContent=locked?'★ ASSINATURA':selected?'REMOVER':'ADICIONAR';button.disabled=locked;button.onclick=()=>toggleDeckCard(c.n);wrap.append(card,button);grid.append(wrap)})}
function openDeck(){editingDeck=[...customDecks[deck]];q('#deckModal').style.setProperty('--deck-color',decks[deck].color);renderDeckBuilder();q('#deckModal').classList.remove('hidden')}
function closeDeck(){q('#deckModal').classList.add('hidden')}
function toggleDeckCard(name){if(editingDeck.includes(name))editingDeck=editingDeck.filter(n=>n!==name);else if(editingDeck.length<6)editingDeck.push(name);else{q('#deckCount').classList.add('invalid');setTimeout(()=>q('#deckCount').classList.remove('invalid'),700);return}renderDeckBuilder()}
function resetDeckBuilder(){editingDeck=defaultDeck(deck);renderDeckBuilder()}
function saveDeckBuilder(){if(editingDeck.length!==6){q('#deckCount').classList.add('invalid');return}customDecks[deck]=[...editingDeck];saveProgress();closeDeck();q('#deckDetail').querySelector('small').textContent='Baralho salvo: 6 cartas • assinatura garantida.'}
function shopItem(name,note,color,state,price,action){const b=document.createElement('button');b.className='shop-item '+(state.owned?'owned ':'')+(state.selected?'selected':'');b.style.setProperty('--item-color',color);b.innerHTML=`<span class="shop-swatch"></span><span class="shop-note">${note}</span><b>${name}</b><em>${state.selected?'✓ SELECIONADA':state.owned?'USAR':'⚙ '+price+' SUCATA'}</em>`;b.onclick=action;return b}
function shopFail(){const w=q('#shopWallet');w.classList.add('poor');w.firstChild.textContent='SUCATA INSUFICIENTE ';setTimeout(()=>{w.classList.remove('poor');w.firstChild.textContent='SUCATA DISPONÍVEL '},900)}
function buyFrame(id){const f=FRAMES.find(x=>x.c===id);if(!career.ownedFrames.includes(id)){if(career.scrap<f.price)return shopFail();career.scrap-=f.price;career.ownedFrames.push(id)}career.selectedFrame=id;saveProgress();updateCareer();renderShop()}
function buyTrack(id){const t=TRACK_INFO[id];if(!career.ownedTracks.includes(id)){if(career.scrap<t.price)return shopFail();career.scrap-=t.price;career.ownedTracks.push(id)}career.selectedTrack=id;saveProgress();updateCareer();renderShop()}
function renderShop(){q('#shopScrap').textContent=career.scrap;const fg=q('#frameShop'),mg=q('#musicShop');fg.innerHTML='';mg.innerHTML='';fg.append(shopItem('MODO ALEATÓRIO','Alterna entre suas molduras.','#ffe3a0',{owned:true,selected:career.selectedFrame==='random'},0,()=>{career.selectedFrame='random';saveProgress();renderShop()}));FRAMES.forEach(f=>fg.append(shopItem(f.n,'Moldura 3D para a mesa.',f.color,{owned:career.ownedFrames.includes(f.c),selected:career.selectedFrame===f.c},f.price,()=>buyFrame(f.c))));mg.append(shopItem('MODO ALEATÓRIO','Alterna entre suas trilhas.','#ffe3a0',{owned:true,selected:career.selectedTrack===-1},0,()=>{career.selectedTrack=-1;saveProgress();renderShop()}));TRACK_INFO.forEach((t,i)=>mg.append(shopItem(t.n,t.note,t.color,{owned:career.ownedTracks.includes(i),selected:career.selectedTrack===i},t.price,()=>buyTrack(i))))}
function openShop(){renderShop();q('#shopModal').classList.remove('hidden')}
function closeShop(){q('#shopModal').classList.add('hidden')}
const TUTORIAL=[
 {t:'ESCOLHA UMA CARTA',x:'Toque numa carta da sua mão. Ela será ampliada e mostrará poder, tipo, fileira e habilidade.'},
 {t:'POSICIONE NA PRODUÇÃO',x:'A fileira correta ficará iluminada. Confirme em JOGAR ou toque diretamente na fileira destacada.'},
 {t:'ACOMPANHE OS EFEITOS',x:'Bônus, redução, proteção e compra aparecem sobre a fileira. A carta do rival também será revelada antes de entrar.'},
 {t:'CONSULTE A MESA',x:'Toque em qualquer carta pequena já jogada para ampliá-la. Use ÚLTIMA AÇÃO para rever tudo que aconteceu.'}
];
function renderTutorial(){const s=TUTORIAL[tutorialStep];q('#tutorialNumber').textContent=(tutorialStep+1)+' / '+TUTORIAL.length;q('#tutorialTitle').textContent=s.t;q('#tutorialText').textContent=s.x;q('#nextTutorial').textContent=tutorialStep===TUTORIAL.length-1?'ENTENDI ✓':'PRÓXIMO ›'}
function openTutorial(){tutorialStep=0;renderTutorial();q('#tutorialModal').classList.remove('hidden')}
function closeTutorial(){q('#tutorialModal').classList.add('hidden');try{localStorage.setItem('forjaTutorialV13','ok')}catch(e){}}
function chooseFrame(){const game=q('#game'),old=FRAMES.map(x=>x.c);game.classList.remove(...old);const owned=FRAMES.filter(f=>career.ownedFrames.includes(f.c)),frame=career.selectedFrame==='random'?owned[Math.floor(Math.random()*owned.length)]:FRAMES.find(f=>f.c===career.selectedFrame)||owned[0];game.classList.add(frame.c);q('#frameName').textContent=frame.n}
function fill(target,data,enemy,bonuses){const box=q(target);box.innerHTML='';data.forEach((lane,i)=>{const r=document.createElement('div');r.className='row';r.innerHTML=`<span class="lane">${L[i]}<br><b>${laneValue(data,bonuses,i)}</b></span><div class="slots"></div>`;lane.forEach(c=>r.querySelector('.slots').append(make(c,enemy,true)));box.append(r)})}
function draw(){q('#game').style.setProperty('--deck-color',decks[deck].color);q('#game').style.setProperty('--enemy-color',decks[opponent].color);fill('#enemyRows',ai,true,aiBonus);fill('#playerRows',me,false,meBonus);const h=q('#hand');h.innerHTML='';hand.forEach(c=>h.append(make(c,false,false)));q('#playerScore').textContent=total(me,meBonus);q('#enemyScore').textContent=total(ai,aiBonus);q('#round').textContent=round}
function clearPick(){selected=null;selectedLane=null;q('#playCard').disabled=true;q('#playCard').textContent='SELECIONE UMA CARTA';[...q('#playerRows').children].forEach(r=>{r.classList.remove('target');r.onclick=null})}
function validLanes(c){if(c.n==='EMPILHADEIRA TURBO')return[0,1,2];if(deck==='turbo'&&!meLeaderUsed)return[0,1,2];return[c.l]}
function pick(el,c){if(busy)return;sfx('select');selected=c;const lanes=validLanes(c);selectedLane=lanes.length===1?lanes[0]:null;document.querySelectorAll('.hand .selected').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');q('#cardInfo').innerHTML=`<b>${c.n} • PODER ${c.p} • ${c.r}</b><span>${c.h}</span>`;q('#tip').textContent=lanes.length>1?'Escolha uma fileira iluminada.':'Destino: '+L[c.l]+'.';q('#playCard').disabled=lanes.length>1;q('#playCard').textContent=lanes.length>1?'ESCOLHA A FILEIRA':'JOGAR EM '+L[c.l];[...q('#playerRows').children].forEach((r,i)=>{r.classList.toggle('target',lanes.includes(i));r.onclick=lanes.includes(i)?()=>play(c,i):null})}
function strongest(cards,filter=()=>true){return cards.filter(filter).sort((a,b)=>b.p-a.p)[0]||null}
function weakest(cards,filter=()=>true){return cards.filter(filter).sort((a,b)=>a.p-b.p)[0]||null}
function moveStrongest(own,toLane){let found=null,from=-1;own.forEach((lane,i)=>lane.forEach(c=>{if(i!==toLane&&/Máquina/.test(c.t)&&(!found||c.p>found.p)){found=c;from=i}}));if(found){own[from].splice(own[from].indexOf(found),1);own[toLane].push(found)}return found}
function damageStrongest(st,lane,amount){if(st.enemyShield[lane]){st.enemyShield[lane]=false;return'Proteção anulou a sabotagem'}const target=strongest(st.enemy[lane]);if(!target)return'Nenhum alvo rival';target.p=Math.max(0,target.p-amount);return target.n+' perdeu '+amount+' de poder'}
function drawReserve(side,predicate,lane){const st=state(side),pool=decks[st.key].cards.filter(predicate);if(!pool.length)return null;const c=copy(pool[Math.floor(Math.random()*pool.length)]);if(side==='me')hand.push(c);else st.own[lane].push(c);return c}
function applyLeader(side,c){const st=state(side),used=side==='me'?meLeaderUsed:aiLeaderUsed;if(used)return'';let text='';if(st.key==='rio'&&/Máquina/.test(c.t)){c.p+=2;text='Líder: máquina CNC +2'}else if(st.key==='vulcao'&&c.t==='Máquina pesada'){c.p+=3;text='Líder: máquina pesada +3'}else if(st.key==='elite'){const m=weakest(flat(st.own),x=>/Máquina/.test(x.t)&&x!==c);if(m){m.p+=4;m.repaired=true;text='Líder: '+m.n+' reparada +4'}}if(text){if(side==='me')meLeaderUsed=true;else aiLeaderUsed=true}return text}
function applyAbility(c,side,lane){const st=state(side),key=st.key+':'+c.n,leader=applyLeader(side,c);let text=leader,extra=false;
 if((side==='me'?mePending:aiPending)>0&&/Máquina/.test(c.t)){const bonus=side==='me'?mePending:aiPending;c.p+=bonus;if(side==='me')mePending=0;else aiPending=0;text='Lingote Quente: '+c.n+' recebeu +'+bonus}
 switch(key){
  case'rio:REGULADORA CNC':{const m=strongest(st.own[lane],x=>/Máquina/.test(x.t)&&x!==c);if(m){m.p+=3;text=m.n+' regulada: +3'}break}
  case'rio:TORNO CNC':if(st.own[lane].some(x=>x.n==='REGULADORA CNC')){c.p+=2;text='Torno CNC com reguladora: +2'}break;
  case'rio:INDEX GU800':text='INDEX produzirá +2 no fim da rodada';break;
  case'rio:EMPILHADEIRA TURBO':text='Empilhadeira posicionada em '+L[lane];break;
  case'rio:INSPETORA FINAL':st.shield[lane]=true;text=L[lane]+' protegida contra sabotagem';break;
  case'rio:SETUP PERFEITO':st.own[lane].forEach(x=>{if(x!==c)x.p+=1});text='Setup Perfeito: fileira inteira +1';break;
  case'rio:PONTE ROLANTE':{const m=moveStrongest(st.own,lane);text=m?m.n+' movida para '+L[lane]:'Nenhuma máquina para mover';break}
  case'rio:MANUTENÇÃO':{const m=weakest(flat(st.own),x=>/Máquina/.test(x.t));if(m){m.p+=4;m.repaired=true;text=m.n+' reparada: +4'}break}
  case'rio:GIOVANI':{const m=weakest(flat(st.own),x=>/Máquina/.test(x.t));if(m){m.p+=2;text=m.n+' recebeu ajuste de precisão: +2'}else{c.p+=2;text='Ajuste próprio de precisão: +2'}break}
  case'vulcao:MESTRE FUNDIDOR':st.own[lane].forEach(x=>{if(x!==c)x.p+=1});text='Fundição fortalecida: fileira +1';break;
  case'vulcao:FORNO VULCÃO':text='Forno Vulcão em potência máxima';break;
  case'vulcao:PRENSA TITÃ':if(st.enemy[lane].some(x=>x.t==='Máquina')){c.p+=2;text='Prensa contra máquina leve: +2'}break;
  case'vulcao:LINGOTE QUENTE':if(side==='me')mePending=3;else aiPending=3;text='Próxima máquina receberá +3';break;
  case'vulcao:GUINDASTE PESADO':{const r=drawReserve(side,x=>/Máquina/.test(x.t),lane);text=r?r.n+' puxada da reserva':'Reserva vazia';break}
  case'vulcao:QUALIDADE BRUTA':st.shield[lane]=true;text=L[lane]+' protegida contra redução';break;
  case'vulcao:TÊMPERA TOTAL':{let n=0;flat(st.own).filter(x=>x.t==='Material').forEach(x=>{const b=Math.max(2,x.p-x.base);x.p+=b;n++});text=n?'Bônus de '+n+' materiais duplicados':'Nenhum material em campo';break}
  case'vulcao:AÇO INCANDESCENTE':text=damageStrongest(st,lane,2);break;
  case'vulcao:JONATHAN':text=damageStrongest(st,lane,2);break;
  case'turbo:PILOTO TURBO':{const x=strongest(st.own[lane],y=>y.t==='Logística'&&y!==c);if(x){x.p+=2;text=x.n+' reativada: +2'}break}
  case'turbo:EMPILHADEIRA ELÉTRICA':if((side==='me'?lastMe:lastAi)?.n==='PALLETS URGENTES'){c.p+=2;text='Combo com Pallets: +2'}break;
  case'turbo:DOCA EXPRESSA':extra=true;text='Doca Expressa: jogue outra carta';break;
  case'turbo:PONTE ROLANTE':{const x=moveStrongest(st.own,lane);text=x?x.n+' movida entre fileiras':'Nenhuma máquina para mover';break}
  case'turbo:ESTOQUISTA':{const r=drawReserve(side,x=>x.t==='Material'||x.t==='Carga',lane);text=r?'Carta comprada: '+r.n:'Nenhum material na reserva';break}
  case'turbo:PALLETS URGENTES':{const n=flat(st.own).filter(x=>x.t==='Logística').length;c.p+=n;text='Pallets: +'+n+' por logística';break}
  case'turbo:CAMINHÃO DE CARGA':{const near=lane===0?1:lane-1;st.bonus[near]+=6;text=L[near]+' recebeu +6';break}
  case'turbo:ROTA OTIMIZADA':{let n=0;flat(st.own).filter(x=>x.t==='Carga').forEach(x=>{x.p+=2;n++});text=n+' cargas receberam +2';break}
  case'turbo:JÚLIO':{const x=weakest(flat(st.own),y=>y!==c&&(y.t==='Logística'||y.l===1));if(x){x.p+=2;text=x.n+' recebeu rota segura: +2'}else{c.p+=2;text='Júlio abriu a rota: +2'}break}
  case'elite:TÉCNICA ELITE':{const m=weakest(flat(st.own),x=>/Máquina/.test(x.t)&&x!==c);if(m){m.p+=4;m.repaired=true;st.shield[lane]=true;text=m.n+' reparada +4 e protegida'}break}
  case'elite:OFICINA MÓVEL':{let n=0;flat(st.own).filter(x=>x.t==='Equipe').forEach(x=>{x.p+=1;n++});text=n+' equipes receberam +1';break}
  case'elite:LUBRIFICAÇÃO':{const m=strongest(flat(st.own),x=>/Máquina/.test(x.t));if(m){m.p+=1;m.lubed=true;text=m.n+' lubrificada: +1 agora e no fim'}break}
  case'elite:CALIBRADOR DIGITAL':{const b=Math.max(1,...flat(st.own).filter(x=>x!==c).map(x=>Math.max(0,x.p-x.base)));c.p+=b;text='Calibrador copiou bônus +'+b;break}
  case'elite:SOLDADOR':{const r=drawReserve(side,x=>/Máquina/.test(x.t),lane);text=r?'Máquina recuperada: '+r.n:'Nenhuma máquina na reserva';break}
  case'elite:PEÇA SOBRESSALENTE':st.shield[lane]=true;text=L[lane]+' protegida contra quebra';break;
  case'elite:MECÂNICO CHEFE':{let n=0;flat(st.own).filter(x=>x.repaired).forEach(x=>{x.p+=2;n++});text=n+' máquinas reparadas receberam +2';break}
  case'elite:REPARO URGENTE':{const m=weakest(flat(st.own),x=>/Máquina/.test(x.t));if(m){m.p+=3;m.repaired=true}extra=true;text=(m?m.n+' restaurada +3. ':'')+'Jogue novamente';break}
  case'elite:GABRIEL':{const x=weakest(flat(st.own),y=>y!==c&&y.l===2);if(x){x.p+=2;text=x.n+' recebeu diagnóstico noturno: +2'}else{c.p+=2;text='Diagnóstico próprio: +2'}break}
 }
 const resolved=text||c.n+' ativada';c.lastEffect=resolved;if(side==='me')lastMe=c;else lastAi=c;return{text:resolved,extra}
}
function play(c=selected,lane=selectedLane){if(busy||!c||lane===null||!hand.includes(c))return;busy=true;showBattleCard(c,'me',lane,()=>{if(deck==='turbo'&&!meLeaderUsed&&lane!==c.l)meLeaderUsed=true;hand.splice(hand.indexOf(c),1);c.playedLane=lane;me[lane].push(c);clearPick();sfx('card');const result=applyAbility(c,'me',lane);draw();effect(result.text,'me',result.text.includes('perdeu')?'hit':'bonus',c.n);laneEffect('me',lane,result.text);const pc=q('#playerRows').children[lane].querySelector('.card:last-child');if(pc)pc.classList.add('attack');if(result.extra){busy=false;q('#cardInfo').innerHTML='<b>JOGADA EXTRA</b><span>Escolha outra carta antes da resposta rival.</span>';if(!hand.length)setTimeout(endRound,650);return}setTimeout(()=>enemyMove(false),700)})}
function aiLanes(c){if(c.n==='EMPILHADEIRA TURBO'||(opponent==='turbo'&&!aiLeaderUsed))return[0,1,2];return[c.l]}
function aiScore(c,lane){const own=laneValue(ai,aiBonus,lane),rival=laneValue(me,meBonus,lane),gap=rival-own;let score=c.p;if(gap>0&&gap<=c.p+5)score+=8;if(gap<0)score+=Math.max(0,4-Math.abs(gap)/4);if(/perde|redução|sabotagem/i.test(c.h)&&me[lane].length)score+=5;if(/\+|fortalece|recebe/i.test(c.h)&&ai[lane].length)score+=3;if(/protege/i.test(c.h)&&me[lane].length)score+=2;if(FRIENDS.has(c.n))score+=2;return score}
function chooseAiPlay(){if(!aiHand.length)return null;let choices=[];aiHand.forEach((c,index)=>aiLanes(c).forEach(lane=>choices.push({c,index,lane,score:aiScore(c,lane)+Math.random()*1.5})));let pick;if(difficulty==='easy')pick=choices[Math.floor(Math.random()*choices.length)];else{choices.sort((a,b)=>b.score-a.score);pick=difficulty==='expert'?choices[0]:choices[Math.floor(Math.random()*Math.min(3,choices.length))]}aiHand.splice(pick.index,1);if(opponent==='turbo'&&!aiLeaderUsed&&pick.lane!==pick.c.l)aiLeaderUsed=true;return pick}
function enemyMove(chained=false){const move=chooseAiPlay();if(!move){recordAction('Sem cartas disponíveis nesta rodada.','ai','MÃO VAZIA');busy=false;if(!hand.length)setTimeout(endRound,500);return}const {c,lane}=move;showBattleCard(c,'ai',lane,()=>{ai[lane].push(c);sfx('card');const result=applyAbility(c,'ai',lane);draw();effect(result.text,'ai',result.text.includes('perdeu')?'hit':'bonus',c.n);laneEffect('ai',lane,result.text);const ec=q('#enemyRows').children[lane].querySelector('.card:last-child');if(ec){ec.classList.add('attack');setTimeout(()=>ec.classList.add('spark'),240)}if(result.extra&&!chained)return setTimeout(()=>enemyMove(true),800);setTimeout(()=>{busy=false;if(!hand.length)endRound()},950)})}
function finishRoundEffects(){flat(me).forEach(c=>{if(c.n==='INDEX GU800')c.p+=2;if(c.lubed)c.p+=1});flat(ai).forEach(c=>{if(c.n==='INDEX GU800')c.p+=2;if(c.lubed)c.p+=1})}
function resetBoard(){me=[[],[],[]];ai=[[],[],[]];meBonus=[0,0,0];aiBonus=[0,0,0];meShield=[false,false,false];aiShield=[false,false,false];mePending=0;aiPending=0;lastMe=null;lastAi=null;meLeaderUsed=false;aiLeaderUsed=false}
function endRound(){if(busy)return;busy=true;clearPick();finishRoundEffects();const a=total(me,meBonus),b=total(ai,aiBonus),won=a>b;if(won)wins++;else losses++;if(won&&flat(me).some(c=>c.n==='FORNO VULCÃO'))fornoPenaltyMe+=2;if(!won&&flat(ai).some(c=>c.n==='FORNO VULCÃO'))fornoPenaltyAi+=2;draw();q('#tip').textContent=won?`RODADA VENCIDA ${a} × ${b}`:`RODADA PERDIDA ${a} × ${b}`;sfx(won?'win':'lose');if(round===3||wins===2||losses===2)return setTimeout(endGame,1000);setTimeout(()=>{round++;resetBoard();hand=deal(deck,'me');aiHand=deal(opponent,'ai');busy=false;q('#cardInfo').innerHTML='<b>NOVA RODADA</b><span>Escolha uma carta para iniciar a produção.</span>';draw();clearPick()},1250)}
function chooseTrackIndex(){const owned=career.ownedTracks.filter(i=>TRACK_INFO[i]);if(career.selectedTrack>=0)return career.selectedTrack;let next=owned[0];if(owned.length>1)while(next===trackIndex)next=owned[Math.floor(Math.random()*owned.length)];return next}
function chooseTrack(){const music=q('#music');trackIndex=chooseTrackIndex();if(!music)return trackIndex;music.src=TRACKS[trackIndex];music.load();return trackIndex}
function startMusic(change=false){if(window.NativeAudio){soundOn=NativeAudio.isOn();if(change&&soundOn){trackIndex=chooseTrackIndex();if(NativeAudio.playTrack)NativeAudio.playTrack(trackIndex);else NativeAudio.playRandom();setTimeout(()=>NativeAudio.ensurePlaying(),450)}syncSound();return}const music=q('#music');if(!soundOn||!music)return;if(change||trackIndex<0)chooseTrack();music.volume=.65;music.play().then(()=>{soundOn=true;syncSound()}).catch(()=>{soundOn=false;syncSound()})}
function stopMusic(){if(window.NativeAudio){NativeAudio.stop();return}const music=q('#music');if(music)music.pause()}
function syncSound(){q('#sound').classList.toggle('sound-on',soundOn);q('#sound').setAttribute('aria-label',soundOn?'Música ligada':'Música desligada')}
function toggleSound(){if(window.NativeAudio){soundOn=NativeAudio.toggle();syncSound();return}soundOn=!soundOn;if(soundOn)startMusic();else stopMusic();syncSound()}
function revealResult(won){q('#result').classList.remove('hidden');q('#resultTitle').textContent=won?'CONTRATO VENCIDO!':'TURNO PERDIDO';q('#resultText').textContent=won?decks[deck].name+' dominou a produção e conquistou o contrato industrial.':'A '+decks[opponent].name+' fechou o turno à frente. Ajuste seu baralho e tente novamente.';q('#resultReward').textContent='+'+career.lastReward+' SUCATA'}
function endGame(){q('#game').classList.add('hidden');const won=wins>=2,bonus=difficulty==='expert'?50:difficulty==='normal'?20:0;career.matches++;if(won)career.wins++;career.lastReward=won?100+bonus:35;career.scrap+=career.lastReward;saveProgress();updateCareer();const fx=q(won?'#victoryFx':'#defeatFx');fx.classList.remove('hidden');setTimeout(()=>{fx.classList.add('hidden');revealResult(won)},3200)}
function start(){const d=decks[deck],o=decks[d.enemy];opponent=d.enemy;difficulty=q('#difficulty').value;round=1;wins=0;losses=0;actionHistory=[];q('#lastAction').textContent='Aguardando a primeira jogada.';fornoPenaltyMe=0;fornoPenaltyAi=0;resetBoard();hand=deal(deck,'me');aiHand=deal(opponent,'ai');busy=false;selected=null;chooseFrame();q('#factionTitle').textContent=d.name;q('#playerName').textContent=d.name;q('#playerCrest').textContent=d.flag;q('#playerCrest').style.color=d.color;q('#enemyName').textContent=o.name;q('#enemyCrest').textContent=o.flag;q('#enemyCrest').style.color=o.color;q('#menu').classList.add('hidden');q('#result').classList.add('hidden');q('#victoryFx').classList.add('hidden');q('#defeatFx').classList.add('hidden');q('#game').classList.remove('hidden');q('#cardInfo').innerHTML='<b>ESCOLHA UMA CARTA</b><span>Toque nas cartas da mesa para ampliar e consultar.</span>';draw();clearPick();startMusic(true);try{if(!localStorage.getItem('forjaTutorialV13'))setTimeout(openTutorial,350)}catch(e){}}
loadProgress();updateCareer();document.querySelectorAll('[data-deck]').forEach(b=>b.onclick=()=>{deck=b.dataset.deck;const d=decks[deck];document.querySelectorAll('.faction-card').forEach(x=>x.classList.toggle('selected',x===b));q('#deckDetail').innerHTML=`<span class="leader-icon">⚙</span><div><b>${d.name} • ${d.leader}</b><small>${d.leaderText}</small></div>`});q('#difficulty').onchange=()=>{difficulty=q('#difficulty').value;const names={easy:'APRENDIZ',normal:'NORMAL',expert:'ESPECIALISTA'};q('#offlineMode').textContent='OFFLINE CONTRA I.A. • '+names[difficulty]};q('#deckGallery').onclick=openDeck;q('#closeDeck').onclick=closeDeck;q('#resetDeck').onclick=resetDeckBuilder;q('#saveDeck').onclick=saveDeckBuilder;q('#deckModal').onclick=e=>{if(e.target===q('#deckModal'))closeDeck()};q('#howTo').onclick=openTutorial;q('#skipTutorial').onclick=closeTutorial;q('#nextTutorial').onclick=()=>{if(tutorialStep<TUTORIAL.length-1){tutorialStep++;renderTutorial()}else closeTutorial()};q('#play').onclick=start;q('#playCard').onclick=()=>play();q('#sound').onclick=toggleSound;q('#historyBar').onclick=openHistory;q('#closeHistory').onclick=closeHistory;q('#historyModal').onclick=e=>{if(e.target===q('#historyModal'))closeHistory()};q('#closeInspect').onclick=closeInspect;q('#cardInspect').onclick=e=>{if(e.target===q('#cardInspect'))closeInspect()};q('#again').onclick=()=>{stopMusic();q('#result').classList.add('hidden');q('#menu').classList.remove('hidden')};q('#pass').onclick=endRound;q('#back').onclick=()=>{if(!q('#tutorialModal').classList.contains('hidden'))return closeTutorial();if(!q('#deckModal').classList.contains('hidden'))return closeDeck();if(!q('#cardInspect').classList.contains('hidden'))return closeInspect();if(!q('#historyModal').classList.contains('hidden'))return closeHistory();stopMusic();q('#game').classList.add('hidden');q('#menu').classList.remove('hidden')};window.ForjaGame={back:()=>q('#back').click()};
q('#forgeShop').onclick=openShop;q('#closeShop').onclick=closeShop;q('#shopModal').onclick=e=>{if(e.target===q('#shopModal'))closeShop()};const baseBack=q('#back').onclick;q('#back').onclick=()=>{if(!q('#shopModal').classList.contains('hidden'))return closeShop();baseBack()};
let fpsFrames=0,fpsTime=performance.now();function fpsLoop(now){fpsFrames++;if(now-fpsTime>=700){q('#fps').textContent=Math.round(fpsFrames*1000/(now-fpsTime))+' FPS';fpsFrames=0;fpsTime=now}requestAnimationFrame(fpsLoop)}requestAnimationFrame(fpsLoop);
